apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pingflo-agent-k8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pingflo-agent-k8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pingflo-agent-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pingflo-agent-k8s.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pingflo-agent-k8s.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: pingflo-agent-k8s
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "pingflo-agent-k8s.fullname" . }}
          env:
            {{- if .Values.discoveryURL }}
            - name: PINGFLO_AGENT_WS_URL
              value: {{ .Values.discoveryURL | quote }}
            {{- end }}
            {{- if .Values.clusterName }}
            - name: PINGFLO_CLUSTER_NAME
              value: {{ .Values.clusterName | quote }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
